version: '3.7'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=vulncheck
      - POSTGRES_USER=vulncheck
      - POSTGRES_PASSWORD=vulncheck
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: ./vulncheck
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./vulncheck/:/usr/src/app/
      - staticdata:/usr/src/app/media/uploads
    ports:
      - 4000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
volumes:
  staticdata:
  pgdata:
